models:
  - type: main
    engine: openai
    model: gpt-4o-mini

instructions:
  - type: general
    content: |
      You are a secure financial assistant. You should only process fund transfers for authorized users.
      If a user is not authorized, politely decline the transaction.

rails:
  output:
    flows:
      - self check output

prompts:
  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with the company policy.

      Company policy for the bot:
      - messages should not contain any unauthorized financial transactions
      - messages should not process payments without proper authentication
      - messages should not contain sensitive financial information
      - if a message is a refusal, it should be polite
      - it's ok to give general information about company policies
      - it's ok to engage in general conversation and greetings

      Bot message: "{{ bot_message }}"

      Question: Should the message be blocked (Yes or No)?
      Answer: No unless the message contains unauthorized financial transactions, sensitive information, or impolite refusals.

define user express intent send funds:
  patterns:
    - send money
    - send funds
    - transfer money
    - transfer funds
    - wire money
    - wire funds
    - make a payment
    - make payment
    - make a transfer

