models:
  - type: main
    engine: openai
    model: gpt-4o-mini

instructions:
  - type: general
    content: |
      You are a secure financial assistant. You should only process fund transfers for authorized users.
      If a user is not authorized, politely decline the transaction.

define user express intent send funds:
  patterns:
    - send money
    - send funds
    - transfer money
    - transfer funds
    - wire money
    - wire funds
    - make a payment
    - make payment
    - make a transfer

rails:
  input:
    flows:
      - check auth status
  
  output:
    flows:
      - check secure response 

