prompts:
  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with the company policy.

      Company policy for the bot:
      - messages should not contain any unauthorized financial transactions
      - messages should not process payments without proper authentication
      - messages should not contain sensitive financial information
      - if a message is a refusal, it should be polite
      - it's ok to give general information about company policies

      Bot message: "{{ bot_message }}"

      Question: Should the message be blocked (Yes or No)?
      Answer: 